### ISSUE TITLE
Facebook API service

### ISSUE THREAD

**Issue by codernr** [codernr/band-page-generator#1]
Features:

* retreive page events
* retrieve number of likes on page
* retrieve a specific photo album that is used for "featured on home page" container

**Comment by ghost** [comment]
v3.2 API restricts access to page public data, so to get these infos, you have to do extra work:

Add marketing api to your facebook developer app and request a never expiring token on the admin page from marketing api tools.

Works only if the app is in dev stage and the admin is the page administrator but that is acceptable for personal use instead of hard verification processes
